import test from 'node:test';import assert from 'node:assert/strict';
import {buildTaxonomy,parseTaxonomy,verifySource} from '../src/taxonomy.mjs';
import {classify,POLICY} from '../src/classifier.mjs';
import {demoTaxonomy,demoInput,demoProvider} from '../src/demo.mjs';
import {normalizeInput,normalizeMetadataInput,AppError} from '../public/shared.mjs';
test('actual IAB two-header structure and alphanumeric IDs',()=>{const t=parseTaxonomy('Relational ID System\t\t\tContent Taxonomy v3.1\nUnique ID\tParent\tName\tTier 1\tTier 2\nJLBCU7\t\tEntertainment\tEntertainment\t\n338\tJLBCU7\tMusic\tEntertainment\tMusic\n');assert.equal(t.nodes.size,2);assert.deepEqual(t.nodes.get('338').path,['Entertainment','Music']);});
for(const [label,rows] of [['duplicate',[{id:'x',name:'x'},{id:'x',name:'x'}]],['orphan',[{id:'x',parent:'missing',name:'x'}]],['cycle',[{id:'x',parent:'y',name:'x'},{id:'y',parent:'x',name:'y'}]]])test(`taxonomy rejects ${label}`,()=>assert.throws(()=>buildTaxonomy(rows),{code:'taxonomy_invalid'}));
test('taxonomy refuses corrupt/unreviewed source',async()=>await assert.rejects(verifySource(new TextEncoder().encode('bad data')),{code:'taxonomy_changed'}));
test('demo has multiple true topics and abstains on outro',async()=>{const r=await classify(demoInput(),demoTaxonomy,demoProvider(),{demo:true});assert.equal(r.mode,'fixture_demo');assert.equal(r.segments[0].labels.length,2);assert.equal(r.segments[2].status,'insufficient_evidence');assert.equal(r.usage.http_attempts,0);assert.equal(r.calibration,'not_validated');});
test('only-child edge must be evaluated, not assigned probability one',async()=>{const r=await classify(demoInput(),demoTaxonomy,demoProvider());assert.equal(r.segments[0].evaluations.find(x=>x.category_id==='53').model_probability,0.88);});
test('branch pruning is explicitly partial',async()=>{const r=await classify(demoInput(),demoTaxonomy,demoProvider(),{policy:{...POLICY,maxBranches:1}});assert.equal(r.status,'partial');assert.ok(r.segments[0].warnings.some(x=>x.startsWith('branch_budget')));});
test('long input has explicit omitted ranges, not silent truncation',async()=>{const input=normalizeInput({segments:Array.from({length:10},(_,i)=>({start:i*70,end:i*70+5,text:'A detailed segment discussing educational courses and server operations.'}))});const r=await classify(input,demoTaxonomy,demoProvider());assert.equal(r.coverage.total_text_segments,10);assert.equal(r.coverage.processed_text_segments,8);assert.equal(r.coverage.omitted_segments.length,2);assert.equal(r.status,'partial');});
test('budget exhaustion retains explicit partial state',async()=>{const p=demoProvider();p.evaluate=async()=>{throw new AppError('budget_exhausted','Budget',429);};const r=await classify(demoInput(),demoTaxonomy,p);assert.equal(r.segments[0].status,'partial_budget');assert.equal(r.segments[0].labels.length,0);});
test('provider errors never silently fall back to fixture',async()=>{const p=demoProvider();p.evaluate=async()=>{throw new AppError('provider_error','No',502);};await assert.rejects(classify(demoInput(),demoTaxonomy,p),{code:'provider_error'});});
test('parent/child probability disagreement is not silently calibrated',async()=>{const p=demoProvider();const original=p.evaluate;p.evaluate=async(s,q)=>{const r=await original(s,q);for(const [id,x] of Object.entries(q))if(x.instructions?.category?.endsWith('Business I.T.'))r[id]=0.99;return r;};const r=await classify(demoInput(),demoTaxonomy,p);const leaf=r.segments[0].labels.find(x=>x.category_id==='72');assert.equal(leaf.model_probability,0.99);assert.equal(leaf.path_score,0.88);assert.equal(leaf.hierarchy_consistent,false);});
function metadataProvider(education=.92){const metrics={attempts:0,successful_calls:0,input_tokens:0,output_tokens:0,models:new Set(['fixture'])};return{metrics,async evaluate(_state,questions){return Object.fromEntries(Object.entries(questions).map(([id,q])=>{if(id==='sufficient')return[id,.96];const category=q.instructions.category;return[id,category==='Education'?education:category==='Education > Online Education'?education-.02:.05];}));}};}
test('metadata mode classifies one video evidence unit and can finish without transcript fallback',async()=>{const input=normalizeMetadataInput({video_id:'abcDE_12-34',title:'Complete online cloud course',description:'A detailed recorded course with practical labs.',tags:['online course','cloud'],youtube_category_id:'27'},'abcDE_12-34');const r=await classify(input,demoTaxonomy,metadataProvider());assert.equal(r.classification_mode,'metadata');assert.equal(r.evidence_mode,'metadata_only');assert.equal(r.segments.length,1);assert.equal(r.segments[0].labels[0].category_id,'148');assert.equal(r.fallback_required,false);assert.equal(r.video.metadata.youtube_category_id,'27');});
test('metadata result below fast-path threshold requests transcript fallback',async()=>{const input=normalizeMetadataInput({video_id:'abcDE_12-34',title:'Online course',description:'A recorded learning course.'},'abcDE_12-34');const r=await classify(input,demoTaxonomy,metadataProvider(.8));assert.equal(r.status,'completed');assert.equal(r.fallback_required,true);assert.equal(r.fallback_reason,'low_or_no_confidence');});
